spring:
  application:
    name: security
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  security:
    user:
      name: admin
      password: 1234
      # roles:  ADMIN
mybatis:
  mapper-locations:  classpath:/mapper/**/*.xml
  type-aliases-package: com.jjang051.security.member.dto
  configuration:
    map-underscore-to-camel-case: true