spring:
  application:
    name: security
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  security:
    user:
      name: admin
      password: 1234
      # roles:  ADMIN
  mail:
    host: smtp.naver.com
    port: 465
    username: kevin8899@naver.com
    password: 2VH2MSLZVJME
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations:  classpath:/mapper/**/*.xml
  type-aliases-package: com.jjang051.security.member.dto,com.jjang051.security.board.dto
  configuration:
    map-underscore-to-camel-case: true